// Rust guideline compliant 2026-02-10
//! Integration tests for `#[derive(CSharp)]` on structs with named fields.

#![expect(dead_code, reason = "test structs are only used via derive macro")]

use csharp_rs::CSharp;

#[derive(CSharp)]
struct SimpleStruct {
    name: String,
    level: i32,
    active: bool,
}

#[test]
fn simple_struct_name() {
    assert_eq!(SimpleStruct::csharp_name(), "SimpleStruct");
}

#[test]
fn simple_struct_definition_contains_record() {
    let def = SimpleStruct::csharp_definition();
    assert!(
        def.contains("public sealed record SimpleStruct"),
        "missing record declaration:\n{def}"
    );
}

#[test]
fn simple_struct_definition_contains_properties() {
    let def = SimpleStruct::csharp_definition();
    assert!(
        def.contains("public string Name { get; init; }"),
        "missing Name property:\n{def}"
    );
    assert!(
        def.contains("public int Level { get; init; }"),
        "missing Level property:\n{def}"
    );
    assert!(
        def.contains("public bool Active { get; init; }"),
        "missing Active property:\n{def}"
    );
}

#[test]
fn simple_struct_definition_has_auto_generated_comment() {
    let def = SimpleStruct::csharp_definition();
    assert!(
        def.starts_with("// <auto-generated/>"),
        "missing auto-generated comment:\n{def}"
    );
}

#[test]
fn simple_struct_definition_has_stj_attributes() {
    let def = SimpleStruct::csharp_definition();
    assert!(
        def.contains("using System.Text.Json.Serialization;"),
        "missing using directive:\n{def}"
    );
    assert!(
        def.contains("[JsonPropertyName(\"name\")]"),
        "missing JsonPropertyName for name:\n{def}"
    );
    assert!(
        def.contains("[JsonPropertyName(\"level\")]"),
        "missing JsonPropertyName for level:\n{def}"
    );
}

#[test]
fn simple_struct_default_namespace() {
    let def = SimpleStruct::csharp_definition();
    assert!(
        def.contains("namespace Generated"),
        "missing default namespace:\n{def}"
    );
}

// --- struct with rename_all ---

#[derive(CSharp)]
#[serde(rename_all = "camelCase")]
struct PlayerProfile {
    player_id: String,
    display_name: String,
    max_health: i32,
    current_score: f64,
}

#[test]
fn rename_all_camel_case_json_names() {
    let def = PlayerProfile::csharp_definition();
    assert!(
        def.contains("[JsonPropertyName(\"playerId\")]"),
        "missing camelCase playerId:\n{def}"
    );
    assert!(
        def.contains("[JsonPropertyName(\"displayName\")]"),
        "missing camelCase displayName:\n{def}"
    );
    assert!(
        def.contains("[JsonPropertyName(\"maxHealth\")]"),
        "missing camelCase maxHealth:\n{def}"
    );
    assert!(
        def.contains("[JsonPropertyName(\"currentScore\")]"),
        "missing camelCase currentScore:\n{def}"
    );
}

#[test]
fn rename_all_keeps_pascal_case_properties() {
    let def = PlayerProfile::csharp_definition();
    assert!(
        def.contains("public string PlayerId { get; init; }"),
        "missing PascalCase PlayerId:\n{def}"
    );
    assert!(
        def.contains("public string DisplayName { get; init; }"),
        "missing PascalCase DisplayName:\n{def}"
    );
}

// --- struct with namespace override ---

#[derive(CSharp)]
#[csharp(namespace = "PulsarAnvil.Types")]
struct GameConfig {
    difficulty: i32,
}

#[test]
fn namespace_override() {
    let def = GameConfig::csharp_definition();
    assert!(
        def.contains("namespace PulsarAnvil.Types"),
        "missing namespace override:\n{def}"
    );
}

// --- struct with Option fields ---

#[derive(CSharp)]
struct WithOptionals {
    required_field: String,
    optional_score: Option<f64>,
    optional_name: Option<String>,
}

#[test]
fn optional_fields_are_nullable() {
    let def = WithOptionals::csharp_definition();
    assert!(
        def.contains("public string RequiredField { get; init; }"),
        "required field should not be nullable:\n{def}"
    );
    assert!(
        def.contains("public double? OptionalScore { get; init; }"),
        "optional field should be nullable:\n{def}"
    );
    assert!(
        def.contains("public string? OptionalName { get; init; }"),
        "optional string should be nullable:\n{def}"
    );
}

// --- struct with Vec and HashMap ---

use std::collections::HashMap;

#[derive(CSharp)]
struct WithCollections {
    tags: Vec<String>,
    scores: HashMap<String, i32>,
    items: Vec<i64>,
}

#[test]
fn vec_fields_map_to_list() {
    let def = WithCollections::csharp_definition();
    assert!(
        def.contains("public List<string> Tags { get; init; }"),
        "Vec<String> should map to List<string>:\n{def}"
    );
    assert!(
        def.contains("public List<long> Items { get; init; }"),
        "Vec<i64> should map to List<long>:\n{def}"
    );
}

#[test]
fn hashmap_fields_map_to_dictionary() {
    let def = WithCollections::csharp_definition();
    assert!(
        def.contains("public Dictionary<string, int> Scores { get; init; }"),
        "HashMap should map to Dictionary:\n{def}"
    );
}

// --- struct with combined serde + csharp attrs ---

#[derive(CSharp)]
#[serde(rename_all = "PascalCase")]
#[csharp(namespace = "Game.Models")]
struct FullExample {
    player_id: String,
    level: i32,
    score: Option<f64>,
    inventory: Vec<String>,
    metadata: HashMap<String, String>,
}

#[test]
fn full_example_output() {
    let def = FullExample::csharp_definition();

    // Check structure
    assert!(def.contains("// <auto-generated/>"));
    assert!(def.contains("using System.Text.Json.Serialization;"));
    assert!(def.contains("namespace Game.Models"));
    assert!(def.contains("public sealed record FullExample"));

    // Check PascalCase rename_all for JSON names
    assert!(
        def.contains("[JsonPropertyName(\"PlayerId\")]"),
        "JSON name should be PascalCase:\n{def}"
    );
    assert!(def.contains("[JsonPropertyName(\"Level\")]"));
    assert!(def.contains("[JsonPropertyName(\"Score\")]"));

    // Check C# property names are also PascalCase
    assert!(def.contains("public string PlayerId { get; init; }"));
    assert!(def.contains("public int Level { get; init; }"));
    assert!(def.contains("public double? Score { get; init; }"));
    assert!(def.contains("public List<string> Inventory { get; init; }"));
    assert!(def.contains("public Dictionary<string, string> Metadata { get; init; }"));
}

#[test]
fn dependencies_include_field_types() {
    let deps = FullExample::dependencies();
    assert!(deps.contains(&String::from("string")));
    assert!(deps.contains(&String::from("int")));
    assert!(deps.contains(&String::from("double")));
    assert!(deps.contains(&String::from("List<string>")));
}
