// Rust guideline compliant 2026-02-10
//! Token stream generation from the [`DerivedCSharp`] intermediate representation.
//!
//! Produces the `impl CSharp for T` block, including `csharp_name()`,
//! `csharp_definition()`, `dependencies()`, and optionally an export test.

use crate::config::{CSharpConfig, Serializer};
use crate::types::{CSharpField, CSharpVariant, DerivedCSharp, DerivedCSharpKind};
use proc_macro2::TokenStream;
use quote::quote;

impl DerivedCSharp {
    /// Converts the IR into a complete `impl CSharp for T` token stream.
    pub fn into_token_stream(self, config: &CSharpConfig) -> TokenStream {
        let ident = &self.rust_ident;
        let csharp_name = &self.csharp_name;

        let definition_body = self.build_definition(config);
        let dependencies_body = self.build_dependencies();
        let export_test = self.build_export_test(config);

        quote! {
            impl csharp_rs::CSharp for #ident {
                fn csharp_name() -> String {
                    String::from(#csharp_name)
                }

                fn csharp_definition() -> String {
                    #definition_body
                }

                fn dependencies() -> Vec<String> {
                    #dependencies_body
                }
            }

            #export_test
        }
    }

    /// Builds the `csharp_definition()` body that returns a complete `.cs` file.
    fn build_definition(&self, config: &CSharpConfig) -> TokenStream {
        match &self.kind {
            DerivedCSharpKind::Record(fields) => self.build_record_definition(fields, config),
            DerivedCSharpKind::Enum(variants) => self.build_enum_definition(variants, config),
        }
    }

    /// Builds a `sealed record` definition from struct fields.
    fn build_record_definition(
        &self,
        fields: &[CSharpField],
        config: &CSharpConfig,
    ) -> TokenStream {
        let namespace: &str = self.namespace.as_ref();
        let csharp_name = &self.csharp_name;

        let using_directive = match config.serializer {
            Serializer::SystemTextJson => "using System.Text.Json.Serialization;",
            Serializer::Newtonsoft => "using Newtonsoft.Json;",
        };

        let field_exprs: Vec<TokenStream> = fields
            .iter()
            .map(|f| {
                let prop_name = &f.csharp_property_name;
                let json_name = &f.json_name;
                let is_optional = f.is_optional;
                let type_expr = &f.type_expr;

                let attr_name = match config.serializer {
                    Serializer::SystemTextJson => "JsonPropertyName",
                    Serializer::Newtonsoft => "JsonProperty",
                };

                quote! {
                    {
                        let csharp_type = #type_expr;
                        let nullable = if #is_optional { "?" } else { "" };
                        format!(
                            "        [{attr}(\"{json}\")]\n        public {ty}{null} {name} {{ get; init; }}\n",
                            attr = #attr_name,
                            json = #json_name,
                            ty = csharp_type,
                            null = nullable,
                            name = #prop_name,
                        )
                    }
                }
            })
            .collect();

        quote! {
            {
                let mut fields = String::new();
                let field_parts: Vec<String> = vec![#(#field_exprs),*];
                for (i, part) in field_parts.iter().enumerate() {
                    if i > 0 {
                        fields.push('\n');
                    }
                    fields.push_str(part);
                }
                format!(
                    concat!(
                        "// <auto-generated/>\n",
                        "{using}\n",
                        "\n",
                        "namespace {ns}\n",
                        "{{\n",
                        "    public sealed record {name}\n",
                        "    {{\n",
                        "{fields}",
                        "    }}\n",
                        "}}\n",
                    ),
                    using = #using_directive,
                    ns = #namespace,
                    name = #csharp_name,
                    fields = fields,
                )
            }
        }
    }

    /// Builds a `public enum` definition from unit variants.
    ///
    /// All variant information is known at macro expansion time, so the
    /// entire definition is built as a string literal.
    fn build_enum_definition(
        &self,
        variants: &[CSharpVariant],
        config: &CSharpConfig,
    ) -> TokenStream {
        use std::fmt::Write;

        let namespace: &str = self.namespace.as_ref();
        let csharp_name = &self.csharp_name;

        let (using_lines, converter_type) = match config.serializer {
            Serializer::SystemTextJson => (
                "using System.Runtime.Serialization;\nusing System.Text.Json.Serialization;",
                "JsonStringEnumConverter",
            ),
            Serializer::Newtonsoft => (
                "using Newtonsoft.Json;\nusing System.Runtime.Serialization;",
                "StringEnumConverter",
            ),
        };

        let mut variant_block = String::new();
        for v in variants {
            if v.json_name != v.csharp_name {
                writeln!(
                    variant_block,
                    "        [EnumMember(Value = \"{}\")]",
                    v.json_name
                )
                .expect("writing to String never fails");
            }
            writeln!(variant_block, "        {},", v.csharp_name)
                .expect("writing to String never fails");
        }

        let definition = format!(
            concat!(
                "// <auto-generated/>\n",
                "{usings}\n",
                "\n",
                "namespace {ns}\n",
                "{{\n",
                "    [JsonConverter(typeof({converter}))]\n",
                "    public enum {name}\n",
                "    {{\n",
                "{variants}",
                "    }}\n",
                "}}\n",
            ),
            usings = using_lines,
            ns = namespace,
            converter = converter_type,
            name = csharp_name,
            variants = variant_block,
        );

        quote! { String::from(#definition) }
    }

    /// Builds the `dependencies()` body returning type names.
    fn build_dependencies(&self) -> TokenStream {
        match &self.kind {
            DerivedCSharpKind::Record(fields) => {
                let type_exprs: Vec<&TokenStream> = fields.iter().map(|f| &f.type_expr).collect();

                if type_exprs.is_empty() {
                    quote! { Vec::new() }
                } else {
                    quote! {
                        vec![#(#type_exprs),*]
                    }
                }
            }
            DerivedCSharpKind::Enum(_) => quote! { Vec::new() },
        }
    }

    /// Generates an export test function if `export` is enabled.
    fn build_export_test(&self, config: &CSharpConfig) -> TokenStream {
        if !self.export {
            return TokenStream::new();
        }

        let ident = &self.rust_ident;
        let test_name = quote::format_ident!("export_csharp_{}", ident.to_string().to_lowercase());
        let csharp_name = &self.csharp_name;

        let export_dir = self
            .export_to
            .as_ref()
            .map_or_else(|| config.export_dir.display().to_string(), Clone::clone);

        let file_path = format!("{export_dir}/{csharp_name}.cs");

        quote! {
            #[test]
            fn #test_name() {
                csharp_rs::export_to::<#ident>(#file_path)
                    .expect("failed to export C# definition");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CSharpNamespace;
    use std::path::PathBuf;

    /// Helper to build a minimal record IR with one field.
    fn sample_ir(export: bool, export_to: Option<String>) -> DerivedCSharp {
        DerivedCSharp {
            rust_ident: quote::format_ident!("TestStruct"),
            csharp_name: String::from("TestStruct"),
            namespace: CSharpNamespace::new("Test.Ns").unwrap(),
            kind: DerivedCSharpKind::Record(vec![CSharpField {
                csharp_property_name: String::from("Name"),
                json_name: String::from("name"),
                type_expr: quote! { <String as csharp_rs::CSharp>::csharp_name() },
                is_optional: false,
            }]),
            export,
            export_to,
        }
    }

    /// Helper to build a minimal enum IR with variants.
    fn sample_enum_ir() -> DerivedCSharp {
        DerivedCSharp {
            rust_ident: quote::format_ident!("Color"),
            csharp_name: String::from("Color"),
            namespace: CSharpNamespace::new("Test.Ns").unwrap(),
            kind: DerivedCSharpKind::Enum(vec![
                CSharpVariant {
                    csharp_name: String::from("Red"),
                    json_name: String::from("red"),
                },
                CSharpVariant {
                    csharp_name: String::from("Green"),
                    json_name: String::from("green"),
                },
                CSharpVariant {
                    csharp_name: String::from("Blue"),
                    json_name: String::from("Blue"),
                },
            ]),
            export: false,
            export_to: None,
        }
    }

    fn stj_config() -> CSharpConfig {
        CSharpConfig {
            serializer: Serializer::SystemTextJson,
            ..CSharpConfig::default()
        }
    }

    fn newtonsoft_config() -> CSharpConfig {
        CSharpConfig {
            serializer: Serializer::Newtonsoft,
            ..CSharpConfig::default()
        }
    }

    #[test]
    fn stj_token_stream_contains_json_property_name() {
        let ir = sample_ir(false, None);
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            tokens.contains("JsonPropertyName"),
            "STJ output should contain JsonPropertyName:\n{tokens}"
        );
        assert!(
            tokens.contains("System.Text.Json.Serialization"),
            "STJ output should contain using directive:\n{tokens}"
        );
    }

    #[test]
    fn newtonsoft_token_stream_contains_json_property() {
        let ir = sample_ir(false, None);
        let tokens = ir.into_token_stream(&newtonsoft_config()).to_string();
        assert!(
            tokens.contains("JsonProperty"),
            "Newtonsoft output should contain JsonProperty:\n{tokens}"
        );
        assert!(
            tokens.contains("Newtonsoft.Json"),
            "Newtonsoft output should contain using directive:\n{tokens}"
        );
    }

    #[test]
    fn no_export_generates_no_test_fn() {
        let ir = sample_ir(false, None);
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            !tokens.contains("fn export_csharp_"),
            "non-export IR should not generate test function:\n{tokens}"
        );
    }

    #[test]
    fn export_generates_test_fn_with_default_dir() {
        let ir = sample_ir(true, None);
        let config = stj_config();
        let tokens = ir.into_token_stream(&config).to_string();
        assert!(
            tokens.contains("export_csharp_teststruct"),
            "export IR should generate test function:\n{tokens}"
        );
        assert!(
            tokens.contains("csharp-bindings"),
            "should use default export dir:\n{tokens}"
        );
    }

    #[test]
    fn export_to_overrides_directory() {
        let ir = sample_ir(true, Some(String::from("custom/out")));
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            tokens.contains("custom/out"),
            "should use custom export dir:\n{tokens}"
        );
    }

    #[test]
    fn empty_fields_generates_empty_vec_for_dependencies() {
        let ir = DerivedCSharp {
            rust_ident: quote::format_ident!("Empty"),
            csharp_name: String::from("Empty"),
            namespace: CSharpNamespace::new("Ns").unwrap(),
            kind: DerivedCSharpKind::Record(vec![]),
            export: false,
            export_to: None,
        };
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            tokens.contains("Vec :: new ()"),
            "empty fields should use Vec::new() for dependencies:\n{tokens}"
        );
    }

    #[test]
    fn optional_field_generates_nullable_marker() {
        let ir = DerivedCSharp {
            rust_ident: quote::format_ident!("WithOpt"),
            csharp_name: String::from("WithOpt"),
            namespace: CSharpNamespace::new("Ns").unwrap(),
            kind: DerivedCSharpKind::Record(vec![CSharpField {
                csharp_property_name: String::from("Score"),
                json_name: String::from("score"),
                type_expr: quote! { <f64 as csharp_rs::CSharp>::csharp_name() },
                is_optional: true,
            }]),
            export: false,
            export_to: None,
        };
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        // The generated code uses `if #is_optional { "?" }` so true should appear
        assert!(
            tokens.contains("true"),
            "optional field should set is_optional to true:\n{tokens}"
        );
    }

    #[test]
    fn export_test_uses_custom_export_dir_from_config() {
        let ir = sample_ir(true, None);
        let config = CSharpConfig {
            export_dir: PathBuf::from("my/export/path"),
            ..stj_config()
        };
        let tokens = ir.into_token_stream(&config).to_string();
        assert!(
            tokens.contains("my/export/path"),
            "should use config export dir:\n{tokens}"
        );
    }

    #[test]
    fn enum_stj_contains_json_string_enum_converter() {
        let ir = sample_enum_ir();
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            tokens.contains("JsonStringEnumConverter"),
            "STJ enum should contain JsonStringEnumConverter:\n{tokens}"
        );
        assert!(
            tokens.contains("System.Text.Json.Serialization"),
            "STJ enum should contain using directive:\n{tokens}"
        );
    }

    #[test]
    fn enum_newtonsoft_contains_string_enum_converter() {
        let ir = sample_enum_ir();
        let tokens = ir.into_token_stream(&newtonsoft_config()).to_string();
        assert!(
            tokens.contains("StringEnumConverter"),
            "Newtonsoft enum should contain StringEnumConverter:\n{tokens}"
        );
        assert!(
            tokens.contains("Newtonsoft.Json"),
            "Newtonsoft enum should contain using directive:\n{tokens}"
        );
    }

    #[test]
    fn enum_contains_enum_member_only_when_renamed() {
        let ir = sample_enum_ir();
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        // Red→red and Green→green are renamed, Blue→Blue is not
        assert!(
            tokens.contains("EnumMember"),
            "should contain EnumMember for renamed variants:\n{tokens}"
        );
    }

    #[test]
    fn enum_dependencies_returns_empty_vec() {
        let ir = sample_enum_ir();
        let tokens = ir.into_token_stream(&stj_config()).to_string();
        assert!(
            tokens.contains("Vec :: new ()"),
            "enum should use Vec::new() for dependencies:\n{tokens}"
        );
    }
}
