// Rust guideline compliant 2026-02-11
//! Record (sealed record) code generation from struct fields.

use crate::config::{CSharpConfig, CSharpVersion, Serializer};
use crate::types::CSharpField;
use proc_macro2::TokenStream;
use quote::quote;

/// Builds a `sealed record` definition token stream from struct fields.
///
/// The returned token stream evaluates at compile time to produce the complete
/// C# file contents including using directives, namespace, and property
/// declarations with JSON serializer attributes.
///
/// Version-dependent features:
/// - **C# 10+**: file-scoped namespace (`namespace X;` instead of block).
/// - **C# 11+**: `required` modifier on non-optional properties.
pub fn build_record_definition(
    csharp_name: &str,
    namespace: &str,
    fields: &[CSharpField],
    config: &CSharpConfig,
) -> TokenStream {
    let use_file_scoped_ns = config.target >= CSharpVersion::CSharp10;
    let use_required = config.target >= CSharpVersion::CSharp11;

    let using_directive = match config.serializer {
        Serializer::SystemTextJson => "using System.Text.Json.Serialization;",
        Serializer::Newtonsoft => "using Newtonsoft.Json;",
    };

    let prop_indent = if use_file_scoped_ns {
        "    "
    } else {
        "        "
    };

    let field_exprs = build_field_exprs(fields, config, prop_indent, use_required);

    if use_file_scoped_ns {
        build_file_scoped(using_directive, namespace, csharp_name, &field_exprs)
    } else {
        build_block_scoped(using_directive, namespace, csharp_name, &field_exprs)
    }
}

/// Builds token stream expressions for each record property.
///
/// Each expression evaluates at runtime to produce the C# attribute and
/// property declaration for a single field.
fn build_field_exprs(
    fields: &[CSharpField],
    config: &CSharpConfig,
    prop_indent: &str,
    use_required: bool,
) -> Vec<TokenStream> {
    let attr_name = match config.serializer {
        Serializer::SystemTextJson => "JsonPropertyName",
        Serializer::Newtonsoft => "JsonProperty",
    };
    let required_kw = if use_required { "required " } else { "" };

    fields
        .iter()
        .map(|f| {
            let prop_name = &f.csharp_property_name;
            let json_name = &f.json_name;
            let is_optional = f.is_optional;
            let type_expr = &f.type_expr;

            quote! {
                {
                    let csharp_type = #type_expr;
                    let nullable = if #is_optional { "?" } else { "" };
                    let req = if #is_optional { "" } else { #required_kw };
                    format!(
                        "{indent}[{attr}(\"{json}\")]\n{indent}public {req}{ty}{null} {name} {{ get; init; }}\n",
                        indent = #prop_indent,
                        attr = #attr_name,
                        json = #json_name,
                        req = req,
                        ty = csharp_type,
                        null = nullable,
                        name = #prop_name,
                    )
                }
            }
        })
        .collect()
}

/// Builds the final token stream using file-scoped namespace (C# 10+).
fn build_file_scoped(
    using_directive: &str,
    namespace: &str,
    csharp_name: &str,
    field_exprs: &[TokenStream],
) -> TokenStream {
    quote! {
        {
            let mut fields = String::new();
            let field_parts: Vec<String> = vec![#(#field_exprs),*];
            for (i, part) in field_parts.iter().enumerate() {
                if i > 0 {
                    fields.push('\n');
                }
                fields.push_str(part);
            }
            format!(
                concat!(
                    "// <auto-generated/>\n",
                    "{using}\n",
                    "\n",
                    "namespace {ns};\n",
                    "\n",
                    "public sealed record {name}\n",
                    "{{\n",
                    "{fields}",
                    "}}\n",
                ),
                using = #using_directive,
                ns = #namespace,
                name = #csharp_name,
                fields = fields,
            )
        }
    }
}

/// Builds the final token stream using block-scoped namespace (C# 9).
fn build_block_scoped(
    using_directive: &str,
    namespace: &str,
    csharp_name: &str,
    field_exprs: &[TokenStream],
) -> TokenStream {
    quote! {
        {
            let mut fields = String::new();
            let field_parts: Vec<String> = vec![#(#field_exprs),*];
            for (i, part) in field_parts.iter().enumerate() {
                if i > 0 {
                    fields.push('\n');
                }
                fields.push_str(part);
            }
            format!(
                concat!(
                    "// <auto-generated/>\n",
                    "{using}\n",
                    "\n",
                    "namespace {ns}\n",
                    "{{\n",
                    "    public sealed record {name}\n",
                    "    {{\n",
                    "{fields}",
                    "    }}\n",
                    "}}\n",
                ),
                using = #using_directive,
                ns = #namespace,
                name = #csharp_name,
                fields = fields,
            )
        }
    }
}
