// Rust guideline compliant 2026-02-11
//! Record (sealed record) code generation from struct fields.

use crate::config::{CSharpConfig, Serializer};
use crate::types::CSharpField;
use proc_macro2::TokenStream;
use quote::quote;

/// Builds a `sealed record` definition token stream from struct fields.
///
/// The returned token stream evaluates at compile time to produce the complete
/// C# file contents including using directives, namespace, and property
/// declarations with JSON serializer attributes.
pub fn build_record_definition(
    csharp_name: &str,
    namespace: &str,
    fields: &[CSharpField],
    config: &CSharpConfig,
) -> TokenStream {
    let using_directive = match config.serializer {
        Serializer::SystemTextJson => "using System.Text.Json.Serialization;",
        Serializer::Newtonsoft => "using Newtonsoft.Json;",
    };

    let field_exprs: Vec<TokenStream> = fields
        .iter()
        .map(|f| {
            let prop_name = &f.csharp_property_name;
            let json_name = &f.json_name;
            let is_optional = f.is_optional;
            let type_expr = &f.type_expr;

            let attr_name = match config.serializer {
                Serializer::SystemTextJson => "JsonPropertyName",
                Serializer::Newtonsoft => "JsonProperty",
            };

            quote! {
                {
                    let csharp_type = #type_expr;
                    let nullable = if #is_optional { "?" } else { "" };
                    format!(
                        "        [{attr}(\"{json}\")]\n        public {ty}{null} {name} {{ get; init; }}\n",
                        attr = #attr_name,
                        json = #json_name,
                        ty = csharp_type,
                        null = nullable,
                        name = #prop_name,
                    )
                }
            }
        })
        .collect();

    quote! {
        {
            let mut fields = String::new();
            let field_parts: Vec<String> = vec![#(#field_exprs),*];
            for (i, part) in field_parts.iter().enumerate() {
                if i > 0 {
                    fields.push('\n');
                }
                fields.push_str(part);
            }
            format!(
                concat!(
                    "// <auto-generated/>\n",
                    "{using}\n",
                    "\n",
                    "namespace {ns}\n",
                    "{{\n",
                    "    public sealed record {name}\n",
                    "    {{\n",
                    "{fields}",
                    "    }}\n",
                    "}}\n",
                ),
                using = #using_directive,
                ns = #namespace,
                name = #csharp_name,
                fields = fields,
            )
        }
    }
}
