// Rust guideline compliant 2026-02-11
//! Simple enum (public enum) code generation from unit variants.

use crate::config::{CSharpConfig, Serializer};
use crate::types::CSharpVariant;
use proc_macro2::TokenStream;
use quote::quote;

/// Builds a `public enum` definition token stream from unit variants.
///
/// All variant information is known at macro expansion time, so the entire
/// definition is built as a string literal embedded in the token stream.
pub fn build_enum_definition(
    csharp_name: &str,
    namespace: &str,
    variants: &[CSharpVariant],
    config: &CSharpConfig,
) -> TokenStream {
    use std::fmt::Write;

    let (using_lines, converter_type) = match config.serializer {
        Serializer::SystemTextJson => (
            "using System.Runtime.Serialization;\nusing System.Text.Json.Serialization;",
            "JsonStringEnumConverter",
        ),
        Serializer::Newtonsoft => (
            "using Newtonsoft.Json;\nusing System.Runtime.Serialization;",
            "StringEnumConverter",
        ),
    };

    let mut variant_block = String::new();
    for v in variants {
        if v.json_name != v.csharp_name {
            writeln!(
                variant_block,
                "        [EnumMember(Value = \"{}\")]",
                v.json_name
            )
            .expect("writing to String never fails");
        }
        writeln!(variant_block, "        {},", v.csharp_name)
            .expect("writing to String never fails");
    }

    let definition = format!(
        concat!(
            "// <auto-generated/>\n",
            "{usings}\n",
            "\n",
            "namespace {ns}\n",
            "{{\n",
            "    [JsonConverter(typeof({converter}))]\n",
            "    public enum {name}\n",
            "    {{\n",
            "{variants}",
            "    }}\n",
            "}}\n",
        ),
        usings = using_lines,
        ns = namespace,
        converter = converter_type,
        name = csharp_name,
        variants = variant_block,
    );

    quote! { String::from(#definition) }
}
