// Rust guideline compliant 2026-02-14
//! Simple enum (public enum) code generation from unit variants.

use crate::config::{CSharpConfig, CSharpVersion, Serializer};
use crate::types::CSharpVariant;
use proc_macro2::TokenStream;
use quote::quote;

/// Builds a `public enum` definition token stream from unit variants.
///
/// Variant information is known at macro expansion time and is embedded as
/// string literals.  The namespace, however, may resolve at runtime via
/// `cfg.namespace()`, so the final string is assembled inside a `format!`
/// call in the generated code.
///
/// Version-dependent features:
/// - **C# 10+**: file-scoped namespace (`namespace X;` instead of block).
pub fn build_enum_definition(
    csharp_name: &str,
    ns_expr: &TokenStream,
    variants: &[CSharpVariant],
    config: &CSharpConfig,
) -> TokenStream {
    use std::fmt::Write;

    let use_file_scoped_ns = config.target >= CSharpVersion::CSharp10;

    let (using_lines, converter_type) = match config.serializer {
        Serializer::SystemTextJson => (
            "using System.Runtime.Serialization;\nusing System.Text.Json.Serialization;",
            "JsonStringEnumConverter",
        ),
        Serializer::Newtonsoft => (
            "using Newtonsoft.Json;\nusing System.Runtime.Serialization;",
            "StringEnumConverter",
        ),
    };

    // Indentation depends on namespace style.
    let member_indent = if use_file_scoped_ns {
        "    "
    } else {
        "        "
    };
    let type_indent = if use_file_scoped_ns { "" } else { "    " };

    let mut variant_block = String::new();
    for v in variants {
        if v.json_name != v.csharp_name {
            writeln!(
                variant_block,
                "{member_indent}[EnumMember(Value = \"{}\")]",
                v.json_name
            )
            .expect("writing to String never fails");
        }
        writeln!(variant_block, "{member_indent}{},", v.csharp_name)
            .expect("writing to String never fails");
    }

    if use_file_scoped_ns {
        quote! {
            {
                let ns: &str = #ns_expr;
                format!(
                    concat!(
                        "// <auto-generated/>\n",
                        "{usings}\n",
                        "\n",
                        "namespace {ns};\n",
                        "\n",
                        "[JsonConverter(typeof({converter}))]\n",
                        "public enum {name}\n",
                        "{{\n",
                        "{variants}",
                        "}}\n",
                    ),
                    usings = #using_lines,
                    ns = ns,
                    converter = #converter_type,
                    name = #csharp_name,
                    variants = #variant_block,
                )
            }
        }
    } else {
        quote! {
            {
                let ns: &str = #ns_expr;
                format!(
                    concat!(
                        "// <auto-generated/>\n",
                        "{usings}\n",
                        "\n",
                        "namespace {ns}\n",
                        "{{\n",
                        "{ti}[JsonConverter(typeof({converter}))]\n",
                        "{ti}public enum {name}\n",
                        "{ti}{{\n",
                        "{variants}",
                        "{ti}}}\n",
                        "}}\n",
                    ),
                    usings = #using_lines,
                    ns = ns,
                    ti = #type_indent,
                    converter = #converter_type,
                    name = #csharp_name,
                    variants = #variant_block,
                )
            }
        }
    }
}
