// Rust guideline compliant 2026-02-15
//! Simple enum (public enum) code generation from unit variants.

use crate::types::CSharpVariant;
use proc_macro2::TokenStream;
use quote::quote;

/// Builds a `public enum` definition token stream from unit variants.
///
/// Variant information is known at macro expansion time and is embedded as
/// string literals. The namespace may resolve at runtime via
/// `cfg.namespace()`, so the final string is assembled inside a `format!`
/// call in the generated code.
///
/// All configuration decisions (serializer library, C# version) are deferred
/// to runtime via `cfg: &csharp_rs::Config`, which is in scope in the
/// generated `csharp_definition(cfg)` method body.
///
/// Version-dependent features:
/// - **C# 10+**: file-scoped namespace (`namespace X;` instead of block).
pub fn build_enum_definition(
    csharp_name: &str,
    ns_expr: &TokenStream,
    variants: &[CSharpVariant],
) -> TokenStream {
    let variant_members = build_variant_members(variants);

    quote! {
        {
            let ns: &str = #ns_expr;

            // Runtime serializer selection
            let using_lines = match cfg.serializer() {
                csharp_rs::Serializer::SystemTextJson => {
                    "using System.Runtime.Serialization;\nusing System.Text.Json.Serialization;"
                }
                csharp_rs::Serializer::Newtonsoft => {
                    "using Newtonsoft.Json;\nusing System.Runtime.Serialization;"
                }
            };
            let converter_type = match cfg.serializer() {
                csharp_rs::Serializer::SystemTextJson => "JsonStringEnumConverter",
                csharp_rs::Serializer::Newtonsoft => "StringEnumConverter",
            };

            // Runtime version selection
            let use_file_scoped = cfg.target() >= csharp_rs::CSharpVersion::CSharp10;
            let member_indent = if use_file_scoped { "    " } else { "        " };
            let type_indent = if use_file_scoped { "" } else { "    " };

            // Build variant block
            let mut variant_block = String::new();
            #(#variant_members)*

            if use_file_scoped {
                format!(
                    concat!(
                        "// <auto-generated/>\n",
                        "{usings}\n",
                        "\n",
                        "namespace {ns};\n",
                        "\n",
                        "[JsonConverter(typeof({converter}))]\n",
                        "public enum {name}\n",
                        "{{\n",
                        "{variants}",
                        "}}\n",
                    ),
                    usings = using_lines,
                    ns = ns,
                    converter = converter_type,
                    name = #csharp_name,
                    variants = variant_block,
                )
            } else {
                format!(
                    concat!(
                        "// <auto-generated/>\n",
                        "{usings}\n",
                        "\n",
                        "namespace {ns}\n",
                        "{{\n",
                        "{ti}[JsonConverter(typeof({converter}))]\n",
                        "{ti}public enum {name}\n",
                        "{ti}{{\n",
                        "{variants}",
                        "{ti}}}\n",
                        "}}\n",
                    ),
                    usings = using_lines,
                    ns = ns,
                    ti = type_indent,
                    converter = converter_type,
                    name = #csharp_name,
                    variants = variant_block,
                )
            }
        }
    }
}

/// Builds token stream statements for each enum variant member.
///
/// Each statement appends one or two lines to a pre-existing
/// `variant_block: String` and `member_indent: &str` variable in scope.
/// When the variant's JSON name differs from its C# name, an
/// `[EnumMember(Value = "...")]` attribute is prepended.
fn build_variant_members(variants: &[CSharpVariant]) -> Vec<TokenStream> {
    variants
        .iter()
        .map(|v| {
            let csharp_name = &v.csharp_name;
            let json_name = &v.json_name;
            let needs_rename = v.json_name != v.csharp_name;

            if needs_rename {
                quote! {
                    variant_block.push_str(&format!(
                        "{}[EnumMember(Value = \"{}\")]\n",
                        member_indent, #json_name,
                    ));
                    variant_block.push_str(&format!(
                        "{}{},\n",
                        member_indent, #csharp_name,
                    ));
                }
            } else {
                quote! {
                    variant_block.push_str(&format!(
                        "{}{},\n",
                        member_indent, #csharp_name,
                    ));
                }
            }
        })
        .collect()
}
